### ISSUE TITLE
About merging multi-frame lidar cloud at the same location

### ISSUE THREAD

**Issue by Icecream-blue-sky** [weiyithu/SurroundOcc#109]
When multi-frame point clouds are fused, there may be multiple point clouds in the same location, and np.configure will keep all the point clouds in the same location instead of just one. 
```python
################## concatenate all static scene segments  ########################
    lidar_pc_list = [dict['lidar_pc'] for dict in dict_list]
    lidar_pc = np.concatenate(lidar_pc_list, axis=1).T
```
Does this matter?

**Comment by SnoopyMark** [comment]
hey，when i try to step through this code, i meet a question in lidar_to_world_to_liadr() in pc = LidarPointCloud(pc.T) and the error is "Error: Pointcloud points must have format: 4×n"。the shape of  pc.T is processed to be 3×n before passed to lidar_to_world_to_liadr() and I wonder whether it's a bug or just an issue with incompatible versions of nuscenes? do you met the same problem?

**Comment by SnoopyMark** [comment]
> hey，when i try to step through this code, i meet a question in lidar_to_world_to_liadr() in pc = LidarPointCloud(pc.T) and the error is "Error: Pointcloud points must have format: 4×n"。the shape of pc.T is processed to be 3×n before passed to lidar_to_world_to_liadr() and I wonder whether it's a bug or just an issue with incompatible versions of nuscenes? do you met the same problem?

quickly solve this problem by changing “pc0 = np.load(os.path.join(pc_seman_path, 'pc_seman_{}.npy'.format(i)))[:,:3]” in line 159 to “pc0 = np.load(os.path.join(pc_seman_path, 'pc_seman_{}.npy'.format(i)))”
