### ISSUE TITLE
Relationship with OpenOccupancy.

### ISSUE THREAD

**Issue by zzj403** [weiyithu/SurroundOcc#11]
I want to know the relationship and differnece of this dataset to OpenOccupancy dataset: [https://github.com/JeffWang987/OpenOccupancy](url)
I noticed that some authers show up in both papers, and the datasets looks similar.

**Comment by weiyithu** [comment]
OpenOccupancy is a benchmark paper which focuses on building the benchmark with human annotations.  SurroundOcc focuses on methods, including both multi-camera  occupancy prediction method and occupancy groundtruth generation method. Our dataset is autolabeled without expensive occupancy annotations.

**Comment by zzj403** [comment]
> OpenOccupancy is a benchmark paper which focuses on building the benchmark with human annotations. SurroundOcc focuses on methods, including both multi-camera occupancy prediction method and occupancy groundtruth generation method. Our dataset is autolabeled without expensive occupancy annotations.

OK~ Thanks!
