### ISSUE TITLE
推理失败，没有点云生成

### ISSUE THREAD

**Issue by FengyuGuo** [weiyithu/SurroundOcc#119]
运行脚本，在in_the_wild数据集上测试。

./tools/dist_inference.sh ./projects/configs/surroundocc/surroundocc_inference.py ./ckpts/r101_dcn_fcos3d_pretrain.pth 1

有遇到类似问题的吗？

相关输出：

load checkpoint from local path: ./ckpts/r101_dcn_fcos3d_pretrain.pth
The model and loaded state dict do not match exactly

size mismatch for img_neck.lateral_convs.0.conv.weight: copying a param with shape torch.Size([256, 512, 1, 1]) from checkpoint, the shape in current model is torch.Size([512, 512, 1, 1]).
size mismatch for img_neck.lateral_convs.0.conv.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([512]).
size mismatch for img_neck.lateral_convs.1.conv.weight: copying a param with shape torch.Size([256, 1024, 1, 1]) from checkpoint, the shape in current model is torch.Size([512, 1024, 1, 1]).
size mismatch for img_neck.lateral_convs.1.conv.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([512]).
size mismatch for img_neck.lateral_convs.2.conv.weight: copying a param with shape torch.Size([256, 2048, 1, 1]) from checkpoint, the shape in current model is torch.Size([512, 2048, 1, 1]).
size mismatch for img_neck.lateral_convs.2.conv.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([512]).
size mismatch for img_neck.fpn_convs.0.conv.weight: copying a param with shape torch.Size([256, 256, 3, 3]) from checkpoint, the shape in current model is torch.Size([512, 512, 3, 3]).
size mismatch for img_neck.fpn_convs.0.conv.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([512]).
size mismatch for img_neck.fpn_convs.1.conv.weight: copying a param with shape torch.Size([256, 256, 3, 3]) from checkpoint, the shape in current model is torch.Size([512, 512, 3, 3]).
size mismatch for img_neck.fpn_convs.1.conv.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([512]).
size mismatch for img_neck.fpn_convs.2.conv.weight: copying a param with shape torch.Size([256, 256, 3, 3]) from checkpoint, the shape in current model is torch.Size([512, 512, 3, 3]).
size mismatch for img_neck.fpn_convs.2.conv.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([512]).
unexpected key in source state_dict: bbox_head.bld_alpha, bbox_head.cls_convs.0.conv.weight, bbox_head.cls_convs.0.conv.bias, bbox_head.cls_convs.0.gn.weight, bbox_head.cls_convs.0.gn.bias, bbox_head.cls_convs.1.conv.weight, bbox_head.cls_convs.1.conv.bias, bbox_head.cls_convs.1.conv.conv_offset.weight, bbox_head.cls_convs.1.conv.conv_offset.bias, bbox_head.cls_convs.1.gn.weight, bbox_head.cls_convs.1.gn.bias, bbox_head.reg_convs.0.conv.weight, bbox_head.reg_convs.0.conv.bias, bbox_head.reg_convs.0.gn.weight, bbox_head.reg_convs.0.gn.bias, bbox_head.reg_convs.1.conv.weight, bbox_head.reg_convs.1.conv.bias, bbox_head.reg_convs.1.conv.conv_offset.weight, bbox_head.reg_convs.1.conv.conv_offset.bias, bbox_head.reg_convs.1.gn.weight, bbox_head.reg_convs.1.gn.bias, bbox_head.conv_cls_prev.0.conv.weight, bbox_head.conv_cls_prev.0.conv.bias, bbox_head.conv_cls_prev.0.gn.weight, bbox_head.conv_cls_prev.0.gn.bias, bbox_head.conv_cls.weight, bbox_head.conv_cls.bias, bbox_head.conv_reg_prevs.0.0.conv.weight, bbox_head.conv_reg_prevs.0.0.conv.bias, bbox_head.conv_reg_prevs.0.0.gn.weight, bbox_head.conv_reg_prevs.0.0.gn.bias, bbox_head.conv_reg_prevs.1.0.conv.weight, bbox_head.conv_reg_prevs.1.0.conv.bias, bbox_head.conv_reg_prevs.1.0.gn.weight, bbox_head.conv_reg_prevs.1.0.gn.bias, bbox_head.conv_reg_prevs.2.0.conv.weight, bbox_head.conv_reg_prevs.2.0.conv.bias, bbox_head.conv_reg_prevs.2.0.gn.weight, bbox_head.conv_reg_prevs.2.0.gn.bias, bbox_head.conv_reg_prevs.3.0.conv.weight, bbox_head.conv_reg_prevs.3.0.conv.bias, bbox_head.conv_reg_prevs.3.0.gn.weight, bbox_head.conv_reg_prevs.3.0.gn.bias, bbox_head.conv_reg_prevs.5.0.conv.weight, bbox_head.conv_reg_prevs.5.0.conv.bias, bbox_head.conv_reg_prevs.5.0.gn.weight, bbox_head.conv_reg_prevs.5.0.gn.bias, bbox_head.conv_regs.0.weight, bbox_head.conv_regs.0.bias, bbox_head.conv_regs.1.weight, bbox_head.conv_regs.1.bias, bbox_head.conv_regs.2.weight, bbox_head.conv_regs.2.bias, bbox_head.conv_regs.3.weight, bbox_head.conv_regs.3.bias, bbox_head.conv_regs.4.weight, bbox_head.conv_regs.4.bias, bbox_head.conv_regs.5.weight, bbox_head.conv_regs.5.bias, bbox_head.conv_dir_cls_prev.0.conv.weight, bbox_head.conv_dir_cls_prev.0.conv.bias, bbox_head.conv_dir_cls_prev.0.gn.weight, bbox_head.conv_dir_cls_prev.0.gn.bias, bbox_head.conv_dir_cls.weight, bbox_head.conv_dir_cls.bias, bbox_head.conv_attr_prev.0.conv.weight, bbox_head.conv_attr_prev.0.conv.bias, bbox_head.conv_attr_prev.0.gn.weight, bbox_head.conv_attr_prev.0.gn.bias, bbox_head.conv_attr.weight, bbox_head.conv_attr.bias, bbox_head.conv_depth_cls_prev.0.conv.weight, bbox_head.conv_depth_cls_prev.0.conv.bias, bbox_head.conv_depth_cls_prev.0.gn.weight, bbox_head.conv_depth_cls_prev.0.gn.bias, bbox_head.conv_depth_cls.weight, bbox_head.conv_depth_cls.bias, bbox_head.conv_centerness_prev.0.conv.weight, bbox_head.conv_centerness_prev.0.conv.bias, bbox_head.conv_centerness_prev.0.gn.weight, bbox_head.conv_centerness_prev.0.gn.bias, bbox_head.conv_centerness.weight, bbox_head.conv_centerness.bias, bbox_head.scales.0.0.scale, bbox_head.scales.0.1.scale, bbox_head.scales.0.2.scale, bbox_head.scales.0.3.scale, bbox_head.scales.1.0.scale, bbox_head.scales.1.1.scale, bbox_head.scales.1.2.scale, bbox_head.scales.1.3.scale, bbox_head.scales.2.0.scale, bbox_head.scales.2.1.scale, bbox_head.scales.2.2.scale, bbox_head.scales.2.3.scale, bbox_head.scales.3.0.scale, bbox_head.scales.3.1.scale, bbox_head.scales.3.2.scale, bbox_head.scales.3.3.scale, bbox_head.scales.4.0.scale, bbox_head.scales.4.1.scale, bbox_head.scales.4.2.scale, bbox_head.scales.4.3.scale, img_neck.fpn_convs.3.conv.weight, img_neck.fpn_convs.3.conv.bias, img_neck.fpn_convs.4.conv.weight, img_neck.fpn_convs.4.conv.bias

missing keys in source state_dict: pts_bbox_head.transformer.0.level_embeds, pts_bbox_head.transformer.0.cams_embeds, pts_bbox_head.transformer.0.encoder.layers.0.attentions.0.deformable_attention.sampling_offsets.weight, pts_bbox_head.transformer.0.encoder.layers.0.attentions.0.deformable_attention.sampling_offsets.bias, pts_bbox_head.transformer.0.encoder.layers.0.attentions.0.deformable_attention.attention_weights.weight, pts_bbox_head.transformer.0.encoder.layers.0.attentions.0.deformable_attention.attention_weights.bias, pts_bbox_head.transformer.0.encoder.layers.0.attentions.0.deformable_attention.value_proj.weight, pts_bbox_head.transformer.0.encoder.layers.0.attentions.0.deformable_attention.value_proj.bias, pts_bbox_head.transformer.0.encoder.layers.0.attentions.0.output_proj.weight, pts_bbox_head.transformer.0.encoder.layers.0.attentions.0.output_proj.bias, pts_bbox_head.transformer.0.encoder.layers.0.ffns.0.layers.0.0.weight, pts_bbox_head.transformer.0.encoder.layers.0.ffns.0.layers.0.0.bias, pts_bbox_head.transformer.0.encoder.layers.0.ffns.0.layers.1.weight, pts_bbox_head.transformer.0.encoder.layers.0.ffns.0.layers.1.bias, pts_bbox_head.transformer.0.encoder.layers.0.norms.0.weight, pts_bbox_head.transformer.0.encoder.layers.0.norms.0.bias, pts_bbox_head.transformer.0.encoder.layers.0.norms.1.weight, pts_bbox_head.transformer.0.encoder.layers.0.norms.1.bias, pts_bbox_head.transformer.0.encoder.layers.0.deblock.0.0.weight, pts_bbox_head.transformer.0.encoder.layers.0.deblock.0.1.weight, pts_bbox_head.transformer.0.encoder.layers.0.deblock.0.1.bias, pts_bbox_head.transformer.0.encoder.layers.0.deblock.1.0.weight, pts_bbox_head.transformer.0.encoder.layers.0.deblock.1.1.weight, pts_bbox_head.transformer.0.encoder.layers.0.deblock.1.1.bias, pts_bbox_head.transformer.0.reference_points.weight, pts_bbox_head.transformer.0.reference_points.bias, pts_bbox_head.transformer.1.level_embeds, pts_bbox_head.transformer.1.cams_embeds, pts_bbox_head.transformer.1.encoder.layers.0.attentions.0.deformable_attention.sampling_offsets.weight, pts_bbox_head.transformer.1.encoder.layers.0.attentions.0.deformable_attention.sampling_offsets.bias, pts_bbox_head.transformer.1.encoder.layers.0.attentions.0.deformable_attention.attention_weights.weight, pts_bbox_head.transformer.1.encoder.layers.0.attentions.0.deformable_attention.attention_weights.bias, pts_bbox_head.transformer.1.encoder.layers.0.attentions.0.deformable_attention.value_proj.weight, pts_bbox_head.transformer.1.encoder.layers.0.attentions.0.deformable_attention.value_proj.bias, pts_bbox_head.transformer.1.encoder.layers.0.attentions.0.output_proj.weight, pts_bbox_head.transformer.1.encoder.layers.0.attentions.0.output_proj.bias, pts_bbox_head.transformer.1.encoder.layers.0.ffns.0.layers.0.0.weight, pts_bbox_head.transformer.1.encoder.layers.0.ffns.0.layers.0.0.bias, pts_bbox_head.transformer.1.encoder.layers.0.ffns.0.layers.1.weight, pts_bbox_head.transformer.1.encoder.layers.0.ffns.0.layers.1.bias, pts_bbox_head.transformer.1.encoder.layers.0.norms.0.weight, pts_bbox_head.transformer.1.encoder.layers.0.norms.0.bias, pts_bbox_head.transformer.1.encoder.layers.0.norms.1.weight, pts_bbox_head.transformer.1.encoder.layers.0.norms.1.bias, pts_bbox_head.transformer.1.encoder.layers.0.deblock.0.0.weight, pts_bbox_head.transformer.1.encoder.layers.0.deblock.0.1.weight, pts_bbox_head.transformer.1.encoder.layers.0.deblock.0.1.bias, pts_bbox_head.transformer.1.encoder.layers.0.deblock.1.0.weight, pts_bbox_head.transformer.1.encoder.layers.0.deblock.1.1.weight, pts_bbox_head.transformer.1.encoder.layers.0.deblock.1.1.bias, pts_bbox_head.transformer.1.encoder.layers.1.attentions.0.deformable_attention.sampling_offsets.weight, pts_bbox_head.transformer.1.encoder.layers.1.attentions.0.deformable_attention.sampling_offsets.bias, pts_bbox_head.transformer.1.encoder.layers.1.attentions.0.deformable_attention.attention_weights.weight, pts_bbox_head.transformer.1.encoder.layers.1.attentions.0.deformable_attention.attention_weights.bias, pts_bbox_head.transformer.1.encoder.layers.1.attentions.0.deformable_attention.value_proj.weight, pts_bbox_head.transformer.1.encoder.layers.1.attentions.0.deformable_attention.value_proj.bias, pts_bbox_head.transformer.1.encoder.layers.1.attentions.0.output_proj.weight, pts_bbox_head.transformer.1.encoder.layers.1.attentions.0.output_proj.bias, pts_bbox_head.transformer.1.encoder.layers.1.ffns.0.layers.0.0.weight, pts_bbox_head.transformer.1.encoder.layers.1.ffns.0.layers.0.0.bias, pts_bbox_head.transformer.1.encoder.layers.1.ffns.0.layers.1.weight, pts_bbox_head.transformer.1.encoder.layers.1.ffns.0.layers.1.bias, pts_bbox_head.transformer.1.encoder.layers.1.norms.0.weight, pts_bbox_head.transformer.1.encoder.layers.1.norms.0.bias, pts_bbox_head.transformer.1.encoder.layers.1.norms.1.weight, pts_bbox_head.transformer.1.encoder.layers.1.norms.1.bias, pts_bbox_head.transformer.1.encoder.layers.1.deblock.0.0.weight, pts_bbox_head.transformer.1.encoder.layers.1.deblock.0.1.weight, pts_bbox_head.transformer.1.encoder.layers.1.deblock.0.1.bias, pts_bbox_head.transformer.1.encoder.layers.1.deblock.1.0.weight, pts_bbox_head.transformer.1.encoder.layers.1.deblock.1.1.weight, pts_bbox_head.transformer.1.encoder.layers.1.deblock.1.1.bias, pts_bbox_head.transformer.1.encoder.layers.2.attentions.0.deformable_attention.sampling_offsets.weight, pts_bbox_head.transformer.1.encoder.layers.2.attentions.0.deformable_attention.sampling_offsets.bias, pts_bbox_head.transformer.1.encoder.layers.2.attentions.0.deformable_attention.attention_weights.weight, pts_bbox_head.transformer.1.encoder.layers.2.attentions.0.deformable_attention.attention_weights.bias, pts_bbox_head.transformer.1.encoder.layers.2.attentions.0.deformable_attention.value_proj.weight, pts_bbox_head.transformer.1.encoder.layers.2.attentions.0.deformable_attention.value_proj.bias, pts_bbox_head.transformer.1.encoder.layers.2.attentions.0.output_proj.weight, pts_bbox_head.transformer.1.encoder.layers.2.attentions.0.output_proj.bias, pts_bbox_head.transformer.1.encoder.layers.2.ffns.0.layers.0.0.weight, pts_bbox_head.transformer.1.encoder.layers.2.ffns.0.layers.0.0.bias, pts_bbox_head.transformer.1.encoder.layers.2.ffns.0.layers.1.weight, pts_bbox_head.transformer.1.encoder.layers.2.ffns.0.layers.1.bias, pts_bbox_head.transformer.1.encoder.layers.2.norms.0.weight, pts_bbox_head.transformer.1.encoder.layers.2.norms.0.bias, pts_bbox_head.transformer.1.encoder.layers.2.norms.1.weight, pts_bbox_head.transformer.1.encoder.layers.2.norms.1.bias, pts_bbox_head.transformer.1.encoder.layers.2.deblock.0.0.weight, pts_bbox_head.transformer.1.encoder.layers.2.deblock.0.1.weight, pts_bbox_head.transformer.1.encoder.layers.2.deblock.0.1.bias, pts_bbox_head.transformer.1.encoder.layers.2.deblock.1.0.weight, pts_bbox_head.transformer.1.encoder.layers.2.deblock.1.1.weight, pts_bbox_head.transformer.1.encoder.layers.2.deblock.1.1.bias, pts_bbox_head.transformer.1.reference_points.weight, pts_bbox_head.transformer.1.reference_points.bias, pts_bbox_head.transformer.2.level_embeds, pts_bbox_head.transformer.2.cams_embeds, pts_bbox_head.transformer.2.encoder.layers.0.attentions.0.deformable_attention.sampling_offsets.weight, pts_bbox_head.transformer.2.encoder.layers.0.attentions.0.deformable_attention.sampling_offsets.bias, pts_bbox_head.transformer.2.encoder.layers.0.attentions.0.deformable_attention.attention_weights.weight, pts_bbox_head.transformer.2.encoder.layers.0.attentions.0.deformable_attention.attention_weights.bias, pts_bbox_head.transformer.2.encoder.layers.0.attentions.0.deformable_attention.value_proj.weight, pts_bbox_head.transformer.2.encoder.layers.0.attentions.0.deformable_attention.value_proj.bias, pts_bbox_head.transformer.2.encoder.layers.0.attentions.0.output_proj.weight, pts_bbox_head.transformer.2.encoder.layers.0.attentions.0.output_proj.bias, pts_bbox_head.transformer.2.encoder.layers.0.ffns.0.layers.0.0.weight, pts_bbox_head.transformer.2.encoder.layers.0.ffns.0.layers.0.0.bias, pts_bbox_head.transformer.2.encoder.layers.0.ffns.0.layers.1.weight, pts_bbox_head.transformer.2.encoder.layers.0.ffns.0.layers.1.bias, pts_bbox_head.transformer.2.encoder.layers.0.norms.0.weight, pts_bbox_head.transformer.2.encoder.layers.0.norms.0.bias, pts_bbox_head.transformer.2.encoder.layers.0.norms.1.weight, pts_bbox_head.transformer.2.encoder.layers.0.norms.1.bias, pts_bbox_head.transformer.2.encoder.layers.0.deblock.0.0.weight, pts_bbox_head.transformer.2.encoder.layers.0.deblock.0.1.weight, pts_bbox_head.transformer.2.encoder.layers.0.deblock.0.1.bias, pts_bbox_head.transformer.2.encoder.layers.0.deblock.1.0.weight, pts_bbox_head.transformer.2.encoder.layers.0.deblock.1.1.weight, pts_bbox_head.transformer.2.encoder.layers.0.deblock.1.1.bias, pts_bbox_head.transformer.2.encoder.layers.1.attentions.0.deformable_attention.sampling_offsets.weight, pts_bbox_head.transformer.2.encoder.layers.1.attentions.0.deformable_attention.sampling_offsets.bias, pts_bbox_head.transformer.2.encoder.layers.1.attentions.0.deformable_attention.attention_weights.weight, pts_bbox_head.transformer.2.encoder.layers.1.attentions.0.deformable_attention.attention_weights.bias, pts_bbox_head.transformer.2.encoder.layers.1.attentions.0.deformable_attention.value_proj.weight, pts_bbox_head.transformer.2.encoder.layers.1.attentions.0.deformable_attention.value_proj.bias, pts_bbox_head.transformer.2.encoder.layers.1.attentions.0.output_proj.weight, pts_bbox_head.transformer.2.encoder.layers.1.attentions.0.output_proj.bias, pts_bbox_head.transformer.2.encoder.layers.1.ffns.0.layers.0.0.weight, pts_bbox_head.transformer.2.encoder.layers.1.ffns.0.layers.0.0.bias, pts_bbox_head.transformer.2.encoder.layers.1.ffns.0.layers.1.weight, pts_bbox_head.transformer.2.encoder.layers.1.ffns.0.layers.1.bias, pts_bbox_head.transformer.2.encoder.layers.1.norms.0.weight, pts_bbox_head.transformer.2.encoder.layers.1.norms.0.bias, pts_bbox_head.transformer.2.encoder.layers.1.norms.1.weight, pts_bbox_head.transformer.2.encoder.layers.1.norms.1.bias, pts_bbox_head.transformer.2.encoder.layers.1.deblock.0.0.weight, pts_bbox_head.transformer.2.encoder.layers.1.deblock.0.1.weight, pts_bbox_head.transformer.2.encoder.layers.1.deblock.0.1.bias, pts_bbox_head.transformer.2.encoder.layers.1.deblock.1.0.weight, pts_bbox_head.transformer.2.encoder.layers.1.deblock.1.1.weight, pts_bbox_head.transformer.2.encoder.layers.1.deblock.1.1.bias, pts_bbox_head.transformer.2.encoder.layers.2.attentions.0.deformable_attention.sampling_offsets.weight, pts_bbox_head.transformer.2.encoder.layers.2.attentions.0.deformable_attention.sampling_offsets.bias, pts_bbox_head.transformer.2.encoder.layers.2.attentions.0.deformable_attention.attention_weights.weight, pts_bbox_head.transformer.2.encoder.layers.2.attentions.0.deformable_attention.attention_weights.bias, pts_bbox_head.transformer.2.encoder.layers.2.attentions.0.deformable_attention.value_proj.weight, pts_bbox_head.transformer.2.encoder.layers.2.attentions.0.deformable_attention.value_proj.bias, pts_bbox_head.transformer.2.encoder.layers.2.attentions.0.output_proj.weight, pts_bbox_head.transformer.2.encoder.layers.2.attentions.0.output_proj.bias, pts_bbox_head.transformer.2.encoder.layers.2.ffns.0.layers.0.0.weight, pts_bbox_head.transformer.2.encoder.layers.2.ffns.0.layers.0.0.bias, pts_bbox_head.transformer.2.encoder.layers.2.ffns.0.layers.1.weight, pts_bbox_head.transformer.2.encoder.layers.2.ffns.0.layers.1.bias, pts_bbox_head.transformer.2.encoder.layers.2.norms.0.weight, pts_bbox_head.transformer.2.encoder.layers.2.norms.0.bias, pts_bbox_head.transformer.2.encoder.layers.2.norms.1.weight, pts_bbox_head.transformer.2.encoder.layers.2.norms.1.bias, pts_bbox_head.transformer.2.encoder.layers.2.deblock.0.0.weight, pts_bbox_head.transformer.2.encoder.layers.2.deblock.0.1.weight, pts_bbox_head.transformer.2.encoder.layers.2.deblock.0.1.bias, pts_bbox_head.transformer.2.encoder.layers.2.deblock.1.0.weight, pts_bbox_head.transformer.2.encoder.layers.2.deblock.1.1.weight, pts_bbox_head.transformer.2.encoder.layers.2.deblock.1.1.bias, pts_bbox_head.transformer.2.encoder.layers.3.attentions.0.deformable_attention.sampling_offsets.weight, pts_bbox_head.transformer.2.encoder.layers.3.attentions.0.deformable_attention.sampling_offsets.bias, pts_bbox_head.transformer.2.encoder.layers.3.attentions.0.deformable_attention.attention_weights.weight, pts_bbox_head.transformer.2.encoder.layers.3.attentions.0.deformable_attention.attention_weights.bias, pts_bbox_head.transformer.2.encoder.layers.3.attentions.0.deformable_attention.value_proj.weight, pts_bbox_head.transformer.2.encoder.layers.3.attentions.0.deformable_attention.value_proj.bias, pts_bbox_head.transformer.2.encoder.layers.3.attentions.0.output_proj.weight, pts_bbox_head.transformer.2.encoder.layers.3.attentions.0.output_proj.bias, pts_bbox_head.transformer.2.encoder.layers.3.ffns.0.layers.0.0.weight, pts_bbox_head.transformer.2.encoder.layers.3.ffns.0.layers.0.0.bias, pts_bbox_head.transformer.2.encoder.layers.3.ffns.0.layers.1.weight, pts_bbox_head.transformer.2.encoder.layers.3.ffns.0.layers.1.bias, pts_bbox_head.transformer.2.encoder.layers.3.norms.0.weight, pts_bbox_head.transformer.2.encoder.layers.3.norms.0.bias, pts_bbox_head.transformer.2.encoder.layers.3.norms.1.weight, pts_bbox_head.transformer.2.encoder.layers.3.norms.1.bias, pts_bbox_head.transformer.2.encoder.layers.3.deblock.0.0.weight, pts_bbox_head.transformer.2.encoder.layers.3.deblock.0.1.weight, pts_bbox_head.transformer.2.encoder.layers.3.deblock.0.1.bias, pts_bbox_head.transformer.2.encoder.layers.3.deblock.1.0.weight, pts_bbox_head.transformer.2.encoder.layers.3.deblock.1.1.weight, pts_bbox_head.transformer.2.encoder.layers.3.deblock.1.1.bias, pts_bbox_head.transformer.2.encoder.layers.4.attentions.0.deformable_attention.sampling_offsets.weight, pts_bbox_head.transformer.2.encoder.layers.4.attentions.0.deformable_attention.sampling_offsets.bias, pts_bbox_head.transformer.2.encoder.layers.4.attentions.0.deformable_attention.attention_weights.weight, pts_bbox_head.transformer.2.encoder.layers.4.attentions.0.deformable_attention.attention_weights.bias, pts_bbox_head.transformer.2.encoder.layers.4.attentions.0.deformable_attention.value_proj.weight, pts_bbox_head.transformer.2.encoder.layers.4.attentions.0.deformable_attention.value_proj.bias, pts_bbox_head.transformer.2.encoder.layers.4.attentions.0.output_proj.weight, pts_bbox_head.transformer.2.encoder.layers.4.attentions.0.output_proj.bias, pts_bbox_head.transformer.2.encoder.layers.4.ffns.0.layers.0.0.weight, pts_bbox_head.transformer.2.encoder.layers.4.ffns.0.layers.0.0.bias, pts_bbox_head.transformer.2.encoder.layers.4.ffns.0.layers.1.weight, pts_bbox_head.transformer.2.encoder.layers.4.ffns.0.layers.1.bias, pts_bbox_head.transformer.2.encoder.layers.4.norms.0.weight, pts_bbox_head.transformer.2.encoder.layers.4.norms.0.bias, pts_bbox_head.transformer.2.encoder.layers.4.norms.1.weight, pts_bbox_head.transformer.2.encoder.layers.4.norms.1.bias, pts_bbox_head.transformer.2.encoder.layers.4.deblock.0.0.weight, pts_bbox_head.transformer.2.encoder.layers.4.deblock.0.1.weight, pts_bbox_head.transformer.2.encoder.layers.4.deblock.0.1.bias, pts_bbox_head.transformer.2.encoder.layers.4.deblock.1.0.weight, pts_bbox_head.transformer.2.encoder.layers.4.deblock.1.1.weight, pts_bbox_head.transformer.2.encoder.layers.4.deblock.1.1.bias, pts_bbox_head.transformer.2.encoder.layers.5.attentions.0.deformable_attention.sampling_offsets.weight, pts_bbox_head.transformer.2.encoder.layers.5.attentions.0.deformable_attention.sampling_offsets.bias, pts_bbox_head.transformer.2.encoder.layers.5.attentions.0.deformable_attention.attention_weights.weight, pts_bbox_head.transformer.2.encoder.layers.5.attentions.0.deformable_attention.attention_weights.bias, pts_bbox_head.transformer.2.encoder.layers.5.attentions.0.deformable_attention.value_proj.weight, pts_bbox_head.transformer.2.encoder.layers.5.attentions.0.deformable_attention.value_proj.bias, pts_bbox_head.transformer.2.encoder.layers.5.attentions.0.output_proj.weight, pts_bbox_head.transformer.2.encoder.layers.5.attentions.0.output_proj.bias, pts_bbox_head.transformer.2.encoder.layers.5.ffns.0.layers.0.0.weight, pts_bbox_head.transformer.2.encoder.layers.5.ffns.0.layers.0.0.bias, pts_bbox_head.transformer.2.encoder.layers.5.ffns.0.layers.1.weight, pts_bbox_head.transformer.2.encoder.layers.5.ffns.0.layers.1.bias, pts_bbox_head.transformer.2.encoder.layers.5.norms.0.weight, pts_bbox_head.transformer.2.encoder.layers.5.norms.0.bias, pts_bbox_head.transformer.2.encoder.layers.5.norms.1.weight, pts_bbox_head.transformer.2.encoder.layers.5.norms.1.bias, pts_bbox_head.transformer.2.encoder.layers.5.deblock.0.0.weight, pts_bbox_head.transformer.2.encoder.layers.5.deblock.0.1.weight, pts_bbox_head.transformer.2.encoder.layers.5.deblock.0.1.bias, pts_bbox_head.transformer.2.encoder.layers.5.deblock.1.0.weight, pts_bbox_head.transformer.2.encoder.layers.5.deblock.1.1.weight, pts_bbox_head.transformer.2.encoder.layers.5.deblock.1.1.bias, pts_bbox_head.transformer.2.reference_points.weight, pts_bbox_head.transformer.2.reference_points.bias, pts_bbox_head.deblocks.0.0.weight, pts_bbox_head.deblocks.0.1.weight, pts_bbox_head.deblocks.0.1.bias, pts_bbox_head.deblocks.1.0.weight, pts_bbox_head.deblocks.1.1.weight, pts_bbox_head.deblocks.1.1.bias, pts_bbox_head.deblocks.2.0.weight, pts_bbox_head.deblocks.2.1.weight, pts_bbox_head.deblocks.2.1.bias, pts_bbox_head.deblocks.3.0.weight, pts_bbox_head.deblocks.3.1.weight, pts_bbox_head.deblocks.3.1.bias, pts_bbox_head.deblocks.4.0.weight, pts_bbox_head.deblocks.4.1.weight, pts_bbox_head.deblocks.4.1.bias, pts_bbox_head.deblocks.5.0.weight, pts_bbox_head.deblocks.5.1.weight, pts_bbox_head.deblocks.5.1.bias, pts_bbox_head.deblocks.6.0.weight, pts_bbox_head.deblocks.6.1.weight, pts_bbox_head.deblocks.6.1.bias, pts_bbox_head.occ.0.weight, pts_bbox_head.occ.1.weight, pts_bbox_head.occ.2.weight, pts_bbox_head.occ.3.weight, pts_bbox_head.volume_embedding.0.weight, pts_bbox_head.volume_embedding.1.weight, pts_bbox_head.volume_embedding.2.weight, pts_bbox_head.transfer_conv.0.0.weight, pts_bbox_head.transfer_conv.0.0.bias, pts_bbox_head.transfer_conv.1.0.weight, pts_bbox_head.transfer_conv.1.0.bias, pts_bbox_head.transfer_conv.2.0.weight, pts_bbox_head.transfer_conv.2.0.bias

[                                                  ] 0/227, elapsed: 0s, ETA:[Open3D WARNING] Write PLY failed: point cloud has 0 points.
[                                                  ] 1/227, 0.1 task/s, elapsed: 11s, ETA:  2451s[Open3D WARNING] Write PLY failed: point cloud has 0 points.
[                                                  ] 2/227, 0.2 task/s, elapsed: 11s, ETA:  1267s[Open3D WARNING] Write PLY failed: point cloud has 0 points.

**Comment by FengyuGuo** [comment]
I used the wrong checkpoints. problem solved after i use the correct checkpoint. :)

**Comment by lsm2842035890** [comment]
ckpts/r101_dcn_fcos3d_pretrain.pth 不是这个pth吗，是那个2.2G的pth吗
