### ISSUE TITLE
Something wrong with the visulization

### ISSUE THREAD

**Issue by Peize-Liu** [weiyithu/SurroundOcc#120]
Hi,
Thanks for your work. Now I have some issue with the visualization. The only difference is I am running the project in Docker ENV to align the CUDA version.
<img width="861" alt="image" src="https://github.com/user-attachments/assets/09e213f2-f265-45fc-8872-398ee8f098e6">

**Comment by Peize-Liu** [comment]
I get it, the weight provided in Readme and Doc/install.md are different. Use the one in Readme.

**Comment by srmamt00** [comment]
Hi @Peize-Liu,

Kind request. Could you please provide the docker file that you have created for this project. I am facing a lot of issues in setting up SurroundOcc project and also with Docker. It would be really helpful if you could provide me the Dockerfile.

Thanks in advance..!!

**Comment by Peize-Liu** [comment]
> Hi [@Peize-Liu](https://github.com/Peize-Liu),
> 
> Kind request. Could you please provide the docker file that you have created for this project. I am facing a lot of issues in setting up SurroundOcc project and also with Docker. It would be really helpful if you could provide me the Dockerfile.
> 
> Thanks in advance..!!

https://github.com/Peize-Liu/SurroundOcc I updated the dockerfile in my repo.

**Comment by srmamt00** [comment]
Hi @Peize-Liu,

Thank you so much for the prompt reply. I find that most of the lines in Dockerfile.cu11_1 is commented out (Should I uncomment the lines?) and when I run start_docker.sh, I am getting the following error
./start_docker.sh 
Unable to find image 'cuda11_3_pytorch_occ:surroundocc' locally
docker: Error response from daemon: pull access denied for cuda11_3_pytorch_occ, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
Also my current cuda version is 11.8 and I cannot downgrade as I am running in ubuntu 22.04

Sorry to disturb you but can you please provide me the instructions for the setup. I would be really grateful.

Thanks in advance..!!
