### ISSUE TITLE
How do I generate 'occ_path' in nuscenes_infos.pkl ?

### ISSUE THREAD

**Issue by LH-WA** [weiyithu/SurroundOcc#14]
I can't find any code related to key word 'occ_path' in nuscenes_converter.py

**Comment by weiyithu** [comment]
Hi, we provide info pkl file here [https://github.com/weiyithu/SurroundOcc/blob/main/docs/data.md](url) and we do not use nuscenes_converter.py to generate them. If you want to use it, you can add 'occ_path' key and we have updated the related code [https://github.com/weiyithu/SurroundOcc/blob/889d5ca89ec4a6fb7c6c5f54c3d3165f37e11756/tools/data_converter/nuscenes_converter.py#L210](url).
