### ISSUE TITLE
About the training logs

### ISSUE THREAD

**Issue by OrangeSodahub** [weiyithu/SurroundOcc#15]
I wonder if you could provide your training logs in SurroundOcc?

**Comment by weiyithu** [comment]
Hi, here is the training log [https://cloud.tsinghua.edu.cn/f/dd1607528f4f424fa15b/?dl=1](url).

**Comment by OrangeSodahub** [comment]
Thanks

**Comment by Rango-T10000** [comment]
> Hi, here is the training log [https://cloud.tsinghua.edu.cn/f/dd1607528f4f424fa15b/?dl=1](url).

Sorry, the link seems unavailable. Can you share that again? Really thanks.
