### ISSUE TITLE
About the dense labels you provided

### ISSUE THREAD

**Issue by OrangeSodahub** [weiyithu/SurroundOcc#18]
I visualized your labels provided in `prepare_dataset`:
![image](https://user-images.githubusercontent.com/54439582/229475396-2d15fb48-f7ec-4de3-9326-937b52c0cb5c.png)

And it is the dense label? like the right most picture shown as belows:
![image](https://user-images.githubusercontent.com/54439582/229475609-7ca494a4-dc7f-4b00-a96f-cec23ff9ef9a.png)

It looks like there is small difference, like the drivable surface

**Comment by weiyithu** [comment]
Can you provide the file name of this case?

**Comment by OrangeSodahub** [comment]
@weiyithu I randomly chose one. 
![image](https://user-images.githubusercontent.com/54439582/229487826-31bb068c-e715-4516-ada2-6170935e58ec.png)

**Comment by weiyithu** [comment]
![CAM_FRONT](https://user-images.githubusercontent.com/32617425/229491371-79341249-569d-481d-835c-b487c6e3855c.jpg)
Hi, this is a rainy day case. For the rainy day, LiDAR will miss many points, especially for drivable space class.  Our label generation algorithm depends on the quality of single-frame LiDAR point clouds and thus the dense labels also will miss some areas in this case.

**Comment by OrangeSodahub** [comment]
Thanks

**Comment by weiyithu** [comment]
Moreover, there may exists a few noisy points in training set and we will upload a new version generated with the latest code in a few days.

**Comment by OrangeSodahub** [comment]
Thanks

**Comment by weiyithu** [comment]
Hi, we have uploaded a new version training set.
