### ISSUE TITLE
Train SurrOcc using sparse data

### ISSUE THREAD

**Issue by OrangeSodahub** [weiyithu/SurroundOcc#19]
Have you tried to train the SurroundOcc using the sparse occupancy data, which means more holes within the labels, and how would it performance on it, and especially compare the different methods ? Actually we tried a little, but got bad results.

I noticed that your results on sparse/dense data in table 6. And how did you process the sparse ground truth in the multi-scale supervision? Is it same as the dense one like:
https://github.com/weiyithu/SurroundOcc/blob/d346e8ce476817dfd8492226e7b92660955bf89c/projects/mmdet3d_plugin/surroundocc/loss/loss_utils.py#L11-L14

If it's true, I applied it on a dense(above) sparse(below) occupancy data:
![image](https://user-images.githubusercontent.com/54439582/229549797-0f4a3030-66f3-43e9-bf68-86e758c41aa1.png)
Is it what you actually did to obtain the results in paper?

**Comment by weiyithu** [comment]
Yeah, the multi-scale supervision is same with the dense one but I find your dense and sparse data are left-right opposite. I find you ask many questions. Here is my WeChat 18600500891 and we  can have more discussion on WeChat for convenience.
