### ISSUE TITLE
Question for training

### ISSUE THREAD

**Issue by promesse** [weiyithu/SurroundOcc#3]
Have you ever met this problem?
![image](https://user-images.githubusercontent.com/26239060/226077513-e193e3ff-e252-4c8e-a14d-3e256e7c6cdc.png)

**Comment by weiyithu** [comment]
Sorry for the confusing. We have fixed this bug and you can pull the newest codes.

**Comment by promesse** [comment]
> Sorry for the confusing. We have fixed this bug and you can pull the newest codes.

Thanks for reply.
Do I need follow this step again?
![image](https://user-images.githubusercontent.com/26239060/226079074-c15a6baf-f767-47cd-b24b-18ff6a3f5c22.png)

**Comment by weiyithu** [comment]
You do not need since chamfer package is installed in your conda environment.
