### ISSUE TITLE
Question about folder structure of 'nuscenes_occ'

### ISSUE THREAD

**Issue by joonsu0109gh** [weiyithu/SurroundOcc#30]
I wonder what folder is 'nuscenes_occ' and how it is composed.

**Comment by weiyithu** [comment]
Hi, it is just like this:
├── nuscenes_occ/
│     ├── samples/
│     │     ├──  n008-2018-09-18-14-54-39-0400__LIDAR_TOP__1537297541450317.pcd.bin.npy
│     │     ├──  ......
│     │     ├──  n015-2018-11-21-19-58-31+0800__LIDAR_TOP__1542801730947831.pcd.bin.npy
