### ISSUE TITLE
Result of no semantic model

### ISSUE THREAD

**Issue by acse-qj320** [weiyithu/SurroundOcc#35]
Hi, I' m just wondering whether you have some visual result of no semantic model, thanks a lot.

**Comment by weiyithu** [comment]
Hi, we do not visualize the no semantic results in our paper but you can visualize it by our own. You can follow the [instruction ](https://github.com/weiyithu/SurroundOcc/blob/main/docs/run.md). However, for no semantic visualization, you should change the [config](https://github.com/weiyithu/SurroundOcc/blob/6cdbadb94f7603bbff6b15c81783e50fe43ba497/projects/configs/surroundocc/surroundocc_nosemantic.py#L13) as use_semantic=False.

**Comment by acse-qj320** [comment]
Thanks for your reply !
