### ISSUE TITLE
多帧融合融几帧？能否用未来帧？

### ISSUE THREAD

**Issue by zzy-ucas** [weiyithu/SurroundOcc#41]
您好，请教2个问题：
- 多帧融合融合几帧有什么说法么？个人感觉是尽可能覆盖整个地面为好，需要考虑ROI和帧率、以及车速是么？
- 可以融合未来帧么？如果只融合历史帧，当前时刻车前方的点云还是稀疏的，个人感觉可以融合未来帧，因为无论历史还是未来帧，当前时刻都看不到的。

非常感谢！

**Comment by weiyithu** [comment]
同学，你是指的对于模型输入进行多帧融合还是生成gt的时候多帧融合？

**Comment by zzy-ucas** [comment]
您好，生成gt的时候，模型输入不应该用未来帧吧

**Comment by weiyithu** [comment]
生成gt的时候用了一个序列里的所有帧，包括历史帧和未来帧。
