### ISSUE TITLE
The visualization effect does not match the display

### ISSUE THREAD

**Issue by 1438802682** [weiyithu/SurroundOcc#43]
![](https://github.com/weiyithu/SurroundOcc/assets/76150709/70c08e17-2a8c-4fc7-b0c4-2a2625405929)
Hello, may I ask why the occ voxels appear very sparse when I visualize the npy sample data using visual.py? It is different from the dense voxel effect shown in the cover examples. Could you please explain the reason for this?

**Comment by weiyithu** [comment]
Hi，does your result have the resolution 200x200x16 with 0.5m voxel size?

**Comment by 1438802682** [comment]
> Hi，does your result have the resolution 200x200x16 with 0.5m voxel size?

Yes, I am using the following configuration file:

'depth': 12
'min_density': 0.05
'n_threads': -1
'downsample': False
'voxel_size': 0.5
'max_nn': 30
'pc_range': [-50, -50, -5, 50, 50, 3]
'occ_size': [200, 200, 16]
'self_range': [3.0, 3.0, 3.0]

**Comment by weiyithu** [comment]
Hi, do you use the nuscenes data or your own data?

**Comment by JohnFuguiWang** [comment]
> > Hi，does your result have the resolution 200x200x16 with 0.5m voxel size?
> 
> Yes, I am using the following configuration file:
> 
> 'depth': 12 'min_density': 0.05 'n_threads': -1 'downsample': False 'voxel_size': 0.5 'max_nn': 30 'pc_range': [-50, -50, -5, 50, 50, 3] 'occ_size': [200, 200, 16] 'self_range': [3.0, 3.0, 3.0]

Hi, I just visualized the generated gt occupancy and met the same issue as yours. Also, I generated occupancy labels from nuscenes data, and I used the default config setting. The only change I've made was that I edited a few lines of codes in generate_occupancy_nuscenes.py to use nuscenes-mini dataset.
I wonder how did you solve this problem? Looking forward to your generous reply!

**Comment by weiyithu** [comment]
If you visualize the occupancy groundtruth, you should set voxel size as 1 in visual.py since the distance between neighbored voxels is 1.

**Comment by JohnFuguiWang** [comment]
> If you visualize the occupancy groundtruth, you should set voxel size as 1 in visual.py since the distance between neighbored voxels is 1.

Thanks, it works! Thank you for your help.
