### ISSUE TITLE
Training about different resulotion

### ISSUE THREAD

**Issue by vehxianfish** [weiyithu/SurroundOcc#46]
Thanks for your wonderful work. 
If I want to train a network with different resolutions. 
1. Only need to modify the config file? 
2. and the output result resolution are also the same as the input???
3. and how to save the inference result as input occ.npy file
4. `mesh vertices | train` &&  `mesh vertices | val` is not have annotations?
```
point_cloud_range = [-50, -50, -5.0, 50, 50, 3.0]
occ_size = [200, 200, 16]
```
Thanks~

**Comment by weiyithu** [comment]
Hi, the uploaded mesh vertices do not have semantic labels and only supports for no semantic setting. And we  will upload a semantic version in a few weeks. Thus, so far, for semnatic occupancy prediction you cannot increase resolutions but can decrease resolutions such as 1.0m voxel size. You not only need to change occ size but also need to change (volume whz)[https://github.com/weiyithu/SurroundOcc/blob/fe63c0ab2141b718443ecacd3666f1c2c873c494/projects/configs/surroundocc/surroundocc.py#L32], which represents the resolution of different scales. To save the results for visualization, you may refer (here)[https://github.com/weiyithu/SurroundOcc/blob/main/docs/run.md].

**Comment by vehxianfish** [comment]
> 

Thanks
