### ISSUE TITLE
How do you process the occluded voxels when obtaining the GT occupancy?

### ISSUE THREAD

**Issue by yichen928** [weiyithu/SurroundOcc#53]
Thanks for your nice work!

I am not sure how do you process those occluded voxels not covered by LiDAR point clouds (e.g. voxels behind a building). Do you just set them as free space or have some special strategies? I notice you have ignored some voxels but I think the number of occluded voxels should be much larger than the number of your ignored voxels (only hundreds per-scene).

**Comment by weiyithu** [comment]
Hi, we just set them as free space. The ignored voxels come from the original lidar segmentation label and are not annotated by us.

**Comment by yichen928** [comment]
Thank you for your helpful reply!
