### ISSUE TITLE
Incompatible version of importlib-metadata when installing mmdet3d

### ISSUE THREAD

**Issue by JohnFuguiWang** [weiyithu/SurroundOcc#55]
# Environment
ubuntu18.04
cuda 11.1
# Problem description
During the process of installing mmdet3d,  I encounter the problem of incompatible versions between flake8 5.0.4 and importlib-metadata. 
# Problem Reproduction
1. Following the official install.md, I came to step 6 "Install mmdet3d from source code".
2. when running "python setup.py install", it shows dependency conflict that flake8 needs importlib to be < 4.3:
![image](https://github.com/weiyithu/SurroundOcc/assets/100892680/37123e06-2ce0-4ed2-b151-7451ce942baf)
4. I tried to degrade importlib-metadata to 4.2, but when it seemed that mmdet3d and another package "markdown" need importlib-metadata to be >=4.4.
![image](https://github.com/weiyithu/SurroundOcc/assets/100892680/d8c86f4b-3ee5-464a-a929-7fdb5fb3dc6c)
# Question
I've searched the Internet and other issues, but I still can't find the solution. So could anyone please tell me which version of importlib do you use, or the proper process of  installing mmdet3d? Thank you for your generous help!

**Comment by weiyithu** [comment]
Hi, we use import lib-metadata as 4.0.0. And you may refer to #49 to get full pip list.

**Comment by JohnFuguiWang** [comment]
> Hi, we use import lib-metadata as 4.0.0. And you may refer to #49 to get full pip list.

Thank you for your reply! I'll try it again.

**Comment by JohnFuguiWang** [comment]
The conflict comes from the versions of importlib_metadata, flake8 and markdown. I install the specific version of these packages following  issue #49, and finally finish the installation. The issue is closed, and thank weiyithu again.
