### ISSUE TITLE
ModuleNotFoundError: No module named 'mmcv._ext'

### ISSUE THREAD

**Issue by JohnFuguiWang** [weiyithu/SurroundOcc#56]
Hi, when running generate_occupancy_nuscenes.py, I encounter such a problem: ModuleNotFoundError: No module named 'mmcv._ext'. 

I've searched the Internet and found many articles/github issues about it, but most of them said that the reason was a mismatch from versions of CUDA, torch and mmcv-full, which I think I've totally avoid. So I still have no idea about the actual reason of this problem. Did anyone meet with the same issue? And how did you fix it? Thanks for your help! 

Also, here I can post the versions of those packages in my environment: 
CUDA: 11.1
![image](https://github.com/weiyithu/SurroundOcc/assets/100892680/4b62d044-888f-44c0-b47f-ed769bc1a58f)
torch: 1.10.1+cu111
![image](https://github.com/weiyithu/SurroundOcc/assets/100892680/4239d66a-b4ee-4c97-b101-67734ed6ce89)
mmcv-full: 1.4.0
![image](https://github.com/weiyithu/SurroundOcc/assets/100892680/32c6700a-3f92-40fd-9a36-1e8eb465766f)

**Comment by weiyithu** [comment]
Hi, sorry I have not met this error. But I think you may try nvidia-smi and see whether the driver cuda version is right.  
![图片](https://github.com/weiyithu/SurroundOcc/assets/32617425/56b981f0-314c-4012-9e78-b2f6cd651116)
I think it is ok that this version can be a little different with nvcc version but should not too far from it.

**Comment by RONINGOD** [comment]
I solved it by
```
pip uninstall mmcv-full mmdet mmsegmentation
pip install mmcv-full==1.4.0 -f https://download.openmmlab.com/mmcv/dist/cu111/torch1.10.0/index.html
pip install mmdet==2.14.0
pip install mmsegmentation==0.14.1
```

**Comment by JohnFuguiWang** [comment]
> I solved it by
> 
> ```
> pip uninstall mmcv-full mmdet mmsegmentation
> pip install mmcv-full==1.4.0 -f https://download.openmmlab.com/mmcv/dist/cu111/torch1.10.0/index.html
> pip install mmdet==2.14.0
> pip install mmsegmentation==0.14.1
> ```

谢谢兄弟，能跑了！虽然我还是不知道为什么能运行，我记得我之前就尝试过这个方法但没成功；而且新安装的库和卸载的库版本也一样，也不知道为什么重新安装一次就能运行了，我觉得很玄学。
但不管怎么说，这次确实能正常运行了，十分感谢。
