### ISSUE TITLE
Does training support multiple batches?

### ISSUE THREAD

**Issue by promesse** [weiyithu/SurroundOcc#6]
As title

**Comment by promesse** [comment]
> Current model is 1 batch per gpu (RTX 3090) and you can use multiple gpu to realize multiple batches. Or your can decrease model size.

Does a single card support multiple batches? My gpu has 32g of ram

**Comment by weiyithu** [comment]
The memory of rtx 3090 is 24g and it cannot obtain 2 batches in a 32g gpu. If you want to use multi batch in one gpu, you need to reduce model size.
