### ISSUE TITLE
安装库的时候有问题

### ISSUE THREAD

**Issue by xuyanging** [weiyithu/SurroundOcc#62]
你好，我安装scipy-image 这个库的时候出现 gcc版本不兼容的问题

`` 

 × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      + meson setup /tmp/pip-req-build-wmo7dqxe /tmp/pip-req-build-wmo7dqxe/.mesonpy-n3v53qj7/build -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --native-file=/tmp/pip-req-build-wmo7dqxe/.mesonpy-n3v53qj7/build/meson-python-native-file.ini
      The Meson build system
      Version: 1.2.0
      Source dir: /tmp/pip-req-build-wmo7dqxe
      Build dir: /tmp/pip-req-build-wmo7dqxe/.mesonpy-n3v53qj7/build
      Build type: native build
      Project name: scikit-image
      Project version: 0.21.0
      C compiler for the host machine: cc (gcc 6.1.0 "cc (GCC) 6.1.0")
      C linker for the host machine: cc ld.bfd 2.38
      C++ compiler for the host machine: c++ (gcc 6.1.0 "c++ (GCC) 6.1.0")
      C++ linker for the host machine: c++ ld.bfd 2.38
      Host machine cpu family: x86_64
      Host machine cpu: x86_64
      
      ../../meson.build:23:4: ERROR: Problem encountered: scikit-image requires GCC >= 8.0

**Comment by RONINGOD** [comment]
请问解决了吗，换成gcc8还是不行

**Comment by weiyithu** [comment]
您gcc是什么版本的

**Comment by RONINGOD** [comment]
> @weiyithu 需要什么版本的，试了9和7都不行

**Comment by RONINGOD** [comment]
ERROR: Ignored the following versions that require a different python version: 0.20.0 Requires-Python >=3.8; 0.20.0rc2 Requires-Python >=3.8; 0.20.0rc3 Requires-Python >=3.8; 0.20.0rc4 Requires-Python >=3.8; 0.20.0rc5 Requires-Python >=3.8; 0.20.0rc6 Requires-Python >=3.8; 0.20.0rc7 Requires-Python >=3.8; 0.20.0rc8 Requires-Python >=3.8; 0.21.0 Requires-Python >=3.8; 0.21.0rc0 Requires-Python >=3.8; 0.21.0rc1 Requires-Python >=3.8
ERROR: Could not find a version that satisfies the requirement scikit_image==0.21.0 (from versions: 0.7.2, 0.8.0, 0.8.1, 0.8.2, 0.9.0, 0.9.1, 0.9.3, 0.10.0, 0.10.1, 0.11.2, 0.11.3, 0.12.0, 0.12.1, 0.12.2, 0.12.3, 0.13.0, 0.13.1, 0.14.0, 0.14.1, 0.14.2, 0.14.3, 0.14.4, 0.14.5, 0.15.0, 0.16.1, 0.16.2, 0.17.1, 0.17.2, 0.18.0, 0.18.1, 0.18.2, 0.18.3, 0.19.0rc0, 0.19.0, 0.19.1, 0.19.2, 0.19.3)
ERROR: No matching distribution found for scikit_image==0.21.0

是不是不能用3.7的环境

**Comment by weiyithu** [comment]
我看了下，我的环境是python3.7， gcc 6.1.0, scikit-image 0.19.3. 整个的pip list在这里 #49

**Comment by RONINGOD** [comment]
```
conda create -n surroundocc python==3.7
conda activate surroundocc

pip install torch==1.10.1+cu111 torchvision==0.11.2+cu111 torchaudio==0.10.1+cu111 -f https://download.pytorch.org/whl/cu111/torch_stable.html

conda install -c omgarcia gcc-6
pip install mmcv-full==1.4.0 mmdet==2.14.0 mmsegmentation==0.14.1

git clone https://github.com/open-mmlab/mmdetection3d.git
cd mmdetection3d
git checkout v0.17.1 # Other versions may not be compatible.
python setup.py install
pip install scikit_image==0.19.3
pip install lyft-dataset-sdk==0.0.8 numba==0.48.0 nuscenes-devkit==1.1.10 plyfile==0.8.1 networkx==2.2 numpy==1.21.5
pip install timm==0.6.12 open3d==0.9.0.0
cd ../
cd SurroundOcc/extensions/chamfer_dist
python setup.py install --user

cd ../../
mkdir ckpts
cd ckpts & wget https://github.com/zhiqi-li/storage/releases/download/v1.0/r101_dcn_fcos3d_pretrain.pth
```

**Comment by xuyanging** [comment]
解决了，装mmdetection3d的时候不要用作者提到的 `python setup.py install 这个方法，而是遵照官方安装的方式去装
`
