### ISSUE TITLE
Occupancy_GT_generation

### ISSUE THREAD

**Issue by ZirongChan** [weiyithu/SurroundOcc#71]
Hello, thx for releasing the great work.
I am wondering if you could explain more about the the files used for the gt_occupancy_generation.
Maybe just briefing the meaninig and the data structure contained in each npy file under the "calib" directory.
Another question is that should the distortion in each LiDAR point cloud be rectified first before they are fused into the whole sence?

感谢开源这么棒的工作。
刚接触这个方向，想请问关于生成gt_occupancy部分的问题，所使用的数据（格式，含义）是否有更详细的解释说明？或者是直接沿用了nuSences的一些定义？
另外，想请教在对不同帧的雷达点云进行融合前，是否需要对运动引起的单帧雷达点云的畸变先进行矫正？我在process_own_data.py似乎没有找到对应的操作。
期待你们的回复，再次谢谢。

**Comment by ZirongChan** [comment]
@weiyithu @lqzhao 你们好
1、关于所使用的数据的格式和含义，通过阅读代码现在已经清晰很多。

2、但关于雷达点云融合前的畸变矫正，我看https://github.com/weiyithu/SurroundOcc/blob/main/tools/generate_occupancy_with_own_data/process_your_own_data.py这里是对每一帧的点云数据只做静态场景/动态物体的区别，没有畸变矫正。这不会影响生成的GT的准确性吗？

3、关于动态物体在每一帧的位置，我看代码里的操作，是将某个物体在每一帧中对应的点，通过bbox的rz变换到某个坐标系下，将所有点直接融合在一起成为点云，然后再将它们反投影回各个帧，仅保留点云中位于每帧bbox内的那部分，和静态场景点云变换到该帧坐标系下的点云融合后，进行mesh化。
这里我有两个疑惑：
a) bbox的rz,即bbox[:, 6:7]应该是绕Z轴旋转的弧度，但这个旋转将bbox内的点云变换到哪个坐标系呢？这里将所有bbox中的点都进行变换，似乎暗示着bbox内点云变换后所在的坐标系是统一的，这在每一帧雷达/RGB图像做语义实例分割时应如何实现呢？
b) 单纯地将不同帧中的物体点云融合在一起，并无法保证它们有良好的拼接。例如观测到一台3米长的小汽车，但在不同帧观测到的是小汽车不同的部分，简单地将点云放在一起，最后可能形成4米的长度？我理解再将融合后的点云反投影回每一帧的操作，并去掉多余点，可以将每一帧bbox的位置完全填充，也就是说，每一帧的动态物体点云其实仍是由当前帧分割得到的bbox来主导的，因此多帧拼接可能带来的歧义实际不会有太大影响？

期待你们的回复，感谢你们在忙碌之余的耐心解答。

**Comment by ZirongChan** [comment]
@weiyithu 谢谢你的回复
1、我说的畸变是指单帧雷达点云并不是准确的；如果雷达静止不动的情况下转动一圈，那么得到的点云数据看起来都是一些同心圆，这时候它的测量是准确的；但一般使用的时候，雷达是在运动的状态下采集的数据，那其实点云上的每个点相对于那个瞬间的雷达中心的测量虽然是准确的，但是放在”统一的单帧“的角度看，由于雷达中心在转动一圈的过程中是运动的，点云会呈现螺旋状，这就是我所指的畸变。
2、那我可以理解成，这个object被转到的那个坐标系，是在每一帧数据的bbox就给定了，其准确度是依赖于感知算法的bbox的。是这样吗？

**Comment by weiyithu** [comment]
1. 这个问题我确实没有关注，可能因为nus里的数据都是去完畸变的？
2. 是的，是依赖于bbox准确度的。如果bbox不准的话，把多帧结果叠加起来会有重影的现象。

**Comment by ZirongChan** [comment]
1、nus里的数据没有去畸变吧，可以观察到它的地面并非同心圆的。
2、重影的话其实对占用地图GT的准确度影响大吗？

怎么评价一个生成出来的占用地图GT呢？

**Comment by weiyithu** [comment]
1. 那应该是 这点我们没有注意  同学你说的对 如果有畸变的话 先去畸变的效果应该更好
2. 对于GT评价这块现在没有一个完整的定量评价，更多是直接用肉眼看GT的质量，或者将其投影到RGB上看和RGB的匹配程度。

**Comment by ZirongChan** [comment]
突然又想到一点，就是物体的拼接问题。我看流程中为每一帧生成GT时，分别将拼接的静态场景点云，和对应的物体点云，重新变换到当前帧的pose下。
其实静态场景电源在当前帧pose下（多帧融合较稠密）+当前帧的物体点云，不就可以了吗？多帧融合的物体点云是为了让这部分表示某个物体的点云更稠密吗？

**Comment by weiyithu** [comment]
是的  单帧的物体比较稀疏

**Comment by ZirongChan** [comment]
谢谢你的回复，对我很有帮助。

**Comment by ZirongChan** [comment]
谢谢你的回复，对我很有帮助。
