### ISSUE TITLE
Which version of open3d should I use?

### ISSUE THREAD

**Issue by mukif2** [weiyithu/SurroundOcc#8]
As I tried, version <= 0.3.0 cannot work properly on Python 3.7 which is mentioned in your README, while version >= 0.5.0 doesn't have "open3d.geometry.TriangleMesh.create_from_point_cloud_poisson", I wonder if I should use an old version and build from source code?

**Comment by mukif2** [comment]
Finally I use:

**Comment by mukif2** [comment]
Finally solved, I’m using:

**Comment by weiyithu** [comment]
Hi, we use 0.9.0 version and you can try pip install open3d==0.9.0.

**Comment by mukif2** [comment]
Finally solved, I’m using:
Anaconda
Python 3.8
open3d 0.11.0
