### ISSUE TITLE
generate_occupancy_with_own_data

### ISSUE THREAD

**Issue by a1wj1** [weiyithu/SurroundOcc#85]
当我设置with_semantic参数为False的适合，生成的occupancy_gt.npy为什么无法在visual.py里面运行显示，会报如下错误，请问怎么解决?
  File "visual.py", line 42, in <module>
    fov_voxels = fov_voxels[fov_voxels[..., 3] > 0]
IndexError: index 3 is out of bounds for axis 1 with size 3

**Comment by tayir7** [comment]
当你没有语义标签是，你的数据的维度会变成(N,3) ，所有报错了，你改一下就行

**Comment by pedestrain123** [comment]
> 当你没有语义标签是，你的数据的维度会变成(N,3) ，所有报错了，你改一下就行

@tayir7 你好请问我用示例数据生成带语义的occ真值时，进行可视化，只能可视化场景中很小一部分，地面等都没有可视化出来，请问你遇到过这个问题吗？

<img width="840" height="703" alt="Image" src="https://github.com/user-attachments/assets/27f59c1b-6eab-491d-8021-21392dc38a69" />
