### ISSUE TITLE
关于是否使用关键帧生成gt

### ISSUE THREAD

**Issue by SteveJMao** [weiyithu/SurroundOcc#96]
非常感谢你们的开源工作，我在使用你们提供的生成自己gt（不适用语义标签）的代码时，发现物体拖得比较长（有运动拖影）
![image](https://github.com/weiyithu/SurroundOcc/assets/96252640/fb58a10d-5883-43e3-8590-2721e2e030bf)

我使用了扫描频率为20hz的点云数据，前后两帧之间间隔为0.1s（只有关键帧），将10帧数据拼接在一起。请问，这个问题是否是因为我只使用了关键帧（两帧间隔过长）导致的（有关注到论文提及也使用了非关键帧数据）。期待您的解答，谢谢！

**Comment by SteveJMao** [comment]
物体坐标在lidar坐标系下的顺序为xyzlwh；很抱歉犯了低级错误。
再次感谢作者的开源工作！

**Comment by Rango-T10000** [comment]
> 非常感谢你们的开源工作，我在使用你们提供的生成自己gt（不适用语义标签）的代码时，发现物体拖得比较长（有运动拖影） ![image](https://github.com/weiyithu/SurroundOcc/assets/96252640/fb58a10d-5883-43e3-8590-2721e2e030bf)
> 
> 我使用了扫描频率为20hz的点云数据，前后两帧之间间隔为0.1s（只有关键帧），将10帧数据拼接在一起。请问，这个问题是否是因为我只使用了关键帧（两帧间隔过长）导致的（有关注到论文提及也使用了非关键帧数据）。期待您的解答，谢谢！

你好，我也遇到类似的问题，就是只有raw lidar point数据，没有语义标注没有bounding box标注。
请问你是直接将10帧数据拼接在一起叠加吗？但是作者论文中说这样对与静态场景和动态物体没有区分，
所以作者的方法用bounding box把静态场景和动态物体分开，动态物体按照bounding box index叠加。

所以我想问下这个动态物体拖得比较长（有运动拖影）是不是因为就是纯直接将10帧数据拼接在一起叠加导致的吗？
这个可以作为occ的ground truth吗？

只有raw lidar point数据，没有语义标注没有bounding box标注还能用作者的代码进行处理吗？

**Comment by SteveJMao** [comment]
你好 我当时应该是有bbox的标注的 我个人认为 没有任何标注数据是会导致出现很长的拖影，这样的数据是无法被用作GT的
作者的代码是基于nuscenes的标注来进行的，所以无法对于没有任何标注数据的data进行处理。
我的建议是可以寻找一些foundation model来进行粗略的标注，如果想要降低成本的话；如果有足够的成本可以对lidar进行3dbbox的标注，甚至semantic segmentation的标注

**Comment by SteveJMao** [comment]
ps：我当时的问题是由于我的数据的bbox的坐标顺序和nuscenes不一致导致的，不是因为没有标注导致的
有问题欢迎继续交流！

**Comment by Rango-T10000** [comment]
> 你好 我当时应该是有bbox的标注的 我个人认为 没有任何标注数据是会导致出现很长的拖影，这样的数据是无法被用作GT的 作者的代码是基于nuscenes的标注来进行的，所以无法对于没有任何标注数据的data进行处理。 我的建议是可以寻找一些foundation model来进行粗略的标注，如果想要降低成本的话；如果有足够的成本可以对lidar进行3dbbox的标注，甚至semantic segmentation的标注

非常感谢你的回答，我明白了

**Comment by Rango-T10000** [comment]
> ps：我当时的问题是由于我的数据的bbox的坐标顺序和nuscenes不一致导致的，不是因为没有标注导致的 有问题欢迎继续交流！

您好，我想请教一个问题，就是直接用lidar的数据变成voxel后，有很多重复的index，就是可能lidar能扫描到3w~5w个点，但是我把这些点填入我自己设定的occ范围例如：
# grid_range = np.array([-51.2, -51.2, -4.0, 51.2, 51.2, 12.0])
# occ_size = np.array([256,256,40])

有很多点都会映射到同一个voxel中，所以统计点转换为独一无二的voxel就只剩下5k多个。 (这个操作来自其他occ的工作的数据预处理代码)
即：3w~5w points -> 5k voxels；这个非常稀疏：
差不多就是这样：

<img width="562" height="358" alt="Image" src="https://github.com/user-attachments/assets/2ec95acc-16c2-4b03-8cfc-bc923479fe17" />

之前很多用nuscene数据集的我看他们预处理的代码就好像直接用的这个作为gt_occ，作为label。我并没有找到他们纯直接将10帧数据拼接在一起叠加让lidar更密集的处理方式。所以我很好奇他们这个是否是直接用这个稀疏的作为label的。

还有像你这个图片这么密集是纯直接将10帧数据拼接在一起叠加，这个是需要知道每一帧的R，T然后把其他9帧的用R，T转到叠加的那一帧，然后直接合并，再做point-> voxel索引的映射得到的吗？

**Comment by SteveJMao** [comment]
你好 我理解的是 大家比较统一的做法是将之前帧的点云根据RT投影到当前坐标系下弥补一些稀疏的；具体可以参考surround occ的代码

**Comment by Rango-T10000** [comment]
> 你好 我理解的是 大家比较统一的做法是将之前帧的点云根据RT投影到当前坐标系下弥补一些稀疏的；具体可以参考surround occ的代码

好的，感谢

**Comment by pedestrain123** [comment]
@SteveJMao 老哥你好，请教一个问题，我在用仓库里面的示例数据生成gt然后进行可视化时候，怎么发现怪怪的？体素非常稀疏，而且貌似只有动态物体生成的体素，请问是什么原因？其他环境中静态点生成的体素怎么没有？可视化图像如下 

<img width="1626" height="980" alt="Image" src="https://github.com/user-attachments/assets/824a4b0b-b480-44f9-96d7-02d95a4dc7a3" />
