### ISSUE TITLE
bbox in non-keyframes

### ISSUE THREAD

**Issue by freezing-index** [weiyithu/SurroundOcc#99]
尊敬的开发者，

我注意到您在[GitHub Issue #27](https://github.com/weiyithu/SurroundOcc/issues/27#issuecomment-1541844566)中讨论了关于nuScenes中非关键帧bbox的问题。首先，感谢您的工作和讨论。

在您的评论中，您提到在nuScenes的非关键帧也有bbox和bbox token，且通过以下方式获取：
`lidar_path, boxes, _ = nusc.get_sample_data(lidar_data['token'])`

然而，我遇到了一个关于关键帧和非关键帧处理方式的问题，因为以下条件成立：

`nusc.get('sample', current_sd_record['sample_token']) == nusc.get('sample', nusc.get('sample_data', current_sd_record['prev'])['sample_token'])`

即关键帧与非关键帧都指向同一个sample。我很感兴趣了解您是如何获取非关键帧的bbox的。是否可以提供更多的细节或示例代码，以便更好地理解和帮助解决问题？

期待您的回复，谢谢！

**Comment by freezing-index** [comment]
解决了

**Comment by SnoopyMark** [comment]
请问是如何解决的，我个人认为非关键帧sweeps数据是没有任何标注的，只有对应每个sample的samples数据有bbbx标注

**Comment by SnoopyMark** [comment]
所以是nuscenes devkit包提供了差值方式来对非关键帧也生成了bbox吗

**Comment by SnoopyMark** [comment]
> 解决了


所以是nuscenes devkit包提供了插值方式来对非关键帧也生成了bbox吗，还是说直接提供了和关键帧一样的bbox？

**Comment by SnoopyMark** [comment]
> > 解决了
> 
> 所以是nuscenes devkit包提供了插值方式来对非关键帧也生成了bbox吗，还是说直接提供了和关键帧一样的bbox？

我看到了，使用了线性插值

**Comment by freezing-index** [comment]
对的，原始devkit里也有，不好意思现在才看到

**Comment by freezing-index** [comment]
> 了，使用了线性插值

对的，原始devkit里也有，不好意思现在才看到

**Comment by SnoopyMark** [comment]
> 对的，原始devkit里也有，不好意思现在才看到

没事，我刚整明白，看一下源码注释就没明白了
